### ISSUE TITLE
How to show keyboard and request focus to the first item

### ISSUE THREAD

**Issue by antranvn** [DamianvdB/MaterialChecklist#2]
Could you add to read me: How to show keyboard and request focus to the first item?

**Comment by DamianvdB** [comment]
I've added an example to the README.md of how to set the focus on a checklist item at a specific position.

Once you have set the focus on an item, you can get a reference to that view using `window.currentFocus` and use the `InputMethodManager` to show the keyboard.

**Comment by antranvn** [comment]
Thanks @DamianvdB
